[package]
name = "interchain-token-service-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.interchain-token-service]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.4"
