[package]
name = "ping-ping-interchain-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.ping-ping-interchain]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.5"
