[package]
name = "auth-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.auth]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.4"
