[package]
name = "operatable"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/operatable.rs"

[dependencies.multiversx-sc]
version = "0.43.4"

[dependencies]
bitflags = "2.4.1"
